services:
  so-crates:
    image: ghcr.io/dougburks/so-crates:main
    container_name: so-crates
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: ./socrates-data
        target: /data
    restart: unless-stopped
